---
- name: install pip3
  apt: name=python3-pip state=present

- name: install pipenv
  pip: name=pipenv state=present

- name: install flake8
  pip: name=flake8 state=present

- name: install yapf code formatter
  pip: name=yapf state=present

- name: install httpie
  pip: name=httpie state=present

- name: install http-prompt
  pip: name=http_prompt state=present

- name: install stormssh
  pip: name=stormssh state=present
